### ISSUE TITLE
paypal order url

### ISSUE THREAD

**Issue by pmcm4** [idembele70/rachel-website#1] opened 2022-05-12 06:28 UTC
where can i get the paypal order url?

GET_PAYPAL_ORDER_URL

**Comment by idembele70** [comment] 2022-05-12 08:47
hi, it's there : https://api.sandbox.paypal.com/v2/checkout/orders/
to find it you can download paypal postman project there : https://developer.paypal.com/api/rest/
and for the base url you can just google : paypal sandbox base url
for information : https://api.sandbox.paypal.com/ is the base url of the sandebox(testing or delevopement if you want)
and https://api-m.paypal.com is the base url for live(production)

**Comment by idembele70** [comment] 2022-05-12 08:47
![Capture d’écran 2022-05-12 à 10 47 38](https://user-images.githubusercontent.com/71393282/168030859-a09b5689-f9aa-4a5c-833d-9975dcd5262b.png)

**Comment by idembele70** [comment] 2022-05-12 08:50
![Capture d’écran 2022-05-12 à 10 48 24](https://user-images.githubusercontent.com/71393282/168031416-5e4dbd7d-3207-49d2-83df-0f7c61cba763.png)

**Comment by idembele70** [comment] 2022-05-12 08:52
![Capture d’écran 2022-05-12 à 10 50 56](https://user-images.githubusercontent.com/71393282/168031575-66275017-9f40-4c44-8096-771ccb3fc64d.png)
in this folder you can find links there !

**Comment by idembele70** [comment] 2022-05-12 08:53
don't forget to have an account in sandebox for testing your payment process : https://www.sandbox.paypal.com/

**Comment by idembele70** [comment] 2022-05-12 08:54
if you have any question just ping me there, and tell me if the issue is resolved or not.
if i doesn't get and anwser before tomorow i will close the issue thanks you.

**Comment by pmcm4** [comment] 2022-05-12 09:29
Hi thank you for your reply, is this correct?
![image](https://user-images.githubusercontent.com/103233119/168039244-5c8816fd-204e-474d-a8d8-d0ba0132b860.png)

**Comment by pmcm4** [comment] 2022-05-12 09:29
sorry, it's my first time using paypal for payment method

**Comment by idembele70** [comment] 2022-05-12 09:43
hi, yes it look good, test it you will see if it's correct

**Comment by pmcm4** [comment] 2022-05-12 10:12
Thank you sir, I got it working now.

**Closed as completed** 2022-05-12 12:08 UTC

**Comment by pmcm4** [comment] 2022-10-11 09:07
Thank you very much sir!
